name: Deploy Next to MicroK8s

on:
  workflow_dispatch:

env:
  GHCR_REPOSITORY: ghcr.io/mcjiaozi/roll-call
  IMAGE_TAG: ${{ github.sha }}

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}"
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.GHCR_REPOSITORY }}:latest

      - name: Transfer YAML file to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "roll-call.yaml"
          target: "~/projects/"

      - name: Deploy to MicroK8s
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_REPOSITORY,IMAGE_TAG
          script: |
            cd ~/projects/
            
            sed -i "s|\$IMAGE_TAG|$IMAGE_TAG|g" roll-call.yaml
            
            microk8s.kubectl apply -f roll-call.yaml
            
            microk8s.kubectl rollout status deployment/roll-call-deployment